stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:20.10.3
  services:
    - docker:18.09.7-din
  stage: publish
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  interruptible: true
  only:
    refs:
      - main

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment

  before_script:
    - apk update && apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh


  script:
    - ssh -o StrictHostKeyChecking=no -l root 45.32.106.84 "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no -l root 45.32.106.84 "docker pull  $TAG_COMMIT"
    - ssh -o StrictHostKeyChecking=no -l root 45.32.106.84 "docker stop web-steel || true"
    - ssh -o StrictHostKeyChecking=no -l root 45.32.106.84 "docker rm web-steel || true"
    - ssh -o StrictHostKeyChecking=no -l root 45.32.106.84 "docker run -dit --restart=always -p 8080:80 --memory="4g" --name web-steel $TAG_COMMIT"

  only:
    refs:
      - main
